/**
 * UCI module type definitions and function signatures
 * Based on ucode/lib/uci.c
 */

import type { FunctionSignature } from './moduleTypes';
import type { ModuleDefinition, ObjectTypeDefinition, PropertyDefinition } from './registryFactory';
import { formatFunctionDoc, formatFunctionSignature } from './registryFactory';

// Backwards-compat type alias
export type UciFunctionSignature = FunctionSignature;

const functions = new Map<string, FunctionSignature>([
  ["error", {
    name: "error",
    parameters: [],
    returnType: "string | null",
    description: "Returns a string containing a description of the last occurred error or null if there is no error information."
  }],
  ["cursor", {
    name: "cursor",
    parameters: [
      { name: "config_dir", type: "string", optional: true, defaultValue: "/etc/config" },
      { name: "delta_dir", type: "string", optional: true, defaultValue: "/tmp/.uci" },
      { name: "config2_dir", type: "string", optional: true, defaultValue: "/var/run/uci" },
      { name: "flags", type: "object", optional: true }
    ],
    returnType: "uci.cursor | null",
    description: "Instantiate uci cursor. A uci cursor is a context for interacting with uci configuration files."
  }]
]);

// Backwards-compat export
export { functions as uciFunctions };

const cursorMethods = new Map<string, FunctionSignature>([
  ["load", {
    name: "load",
    parameters: [
      { name: "config", type: "string", optional: false }
    ],
    returnType: "boolean | null",
    description: "Explicitly reload configuration file. Returns true if the configuration was successfully loaded."
  }],
  ["unload", {
    name: "unload",
    parameters: [
      { name: "config", type: "string", optional: false }
    ],
    returnType: "boolean | null",
    description: "Explicitly unload configuration file. Returns true if the configuration was successfully unloaded."
  }],
  ["get", {
    name: "get",
    parameters: [
      { name: "config", type: "string", optional: false },
      { name: "section", type: "string", optional: false },
      { name: "option", type: "string", optional: true }
    ],
    returnType: "string | string[] | null",
    description: "Query a single option value or section type. When invoked with three arguments, returns the option value. When invoked with two arguments, returns the section type."
  }],
  ["get_all", {
    name: "get_all",
    parameters: [
      { name: "config", type: "string", optional: false },
      { name: "section", type: "string", optional: true }
    ],
    // Two-arg form returns one `uci.section` (see section_to_uval, uci.c). One-arg form
    // returns a package: an object keyed by section name whose values are `uci.section`
    // (package_to_uval, uci.c). The arg-count distinction is not modeled at the type level,
    // so the union carries both shapes conservatively rather than over-committing.
    returnType: "uci.section | object | null",
    description: "Query a complete section or configuration. When invoked with two arguments, returns all values of the specified section as a uci.section object (with `.type`, `.name`, `.anonymous` meta keys plus one key per option). When invoked with one argument, returns a nested dictionary of all sections keyed by section name (each value a uci.section, additionally carrying `.index`)."
  }],
  ["get_first", {
    name: "get_first",
    parameters: [
      { name: "config", type: "string", optional: false },
      { name: "type", type: "string", optional: false },
      { name: "option", type: "string", optional: true }
    ],
    returnType: "string | string[] | null",
    description: "Query option value or name of first section of given type. When invoked with three arguments, returns the option value. When invoked with two arguments, returns the section name."
  }],
  ["add", {
    name: "add",
    parameters: [
      { name: "config", type: "string", optional: false },
      { name: "type", type: "string", optional: false }
    ],
    returnType: "string | null",
    description: "Add anonymous section to given configuration. Returns the autogenerated, ephemeral name of the added unnamed section."
  }],
  ["set", {
    name: "set",
    parameters: [
      { name: "config", type: "string", optional: false },
      { name: "section", type: "string", optional: false },
      { name: "option_or_type", type: "string", optional: false },
      { name: "value", type: "string | string[] | number | boolean", optional: true }
    ],
    returnType: "boolean | null",
    description: "Set option value or add named section in given configuration. Returns true if the operation succeeded."
  }],
  ["delete", {
    name: "delete",
    parameters: [
      { name: "config", type: "string", optional: false },
      { name: "section", type: "string", optional: false },
      { name: "option", type: "string", optional: true }
    ],
    returnType: "boolean | null",
    description: "Delete an option or section from given configuration. When invoked with three arguments, deletes the option. When invoked with two arguments, deletes the entire section."
  }],
  ["list_append", {
    name: "list_append",
    parameters: [
      { name: "config", type: "string", optional: false },
      { name: "section", type: "string", optional: false },
      { name: "option", type: "string", optional: false },
      { name: "value", type: "string | number | boolean", optional: false }
    ],
    returnType: "boolean | null",
    description: "Add an item to a list option in given configuration. The new value is appended to the end of the list."
  }],
  ["list_remove", {
    name: "list_remove",
    parameters: [
      { name: "config", type: "string", optional: false },
      { name: "section", type: "string", optional: false },
      { name: "option", type: "string", optional: false },
      { name: "value", type: "string | number | boolean", optional: false }
    ],
    returnType: "boolean | null",
    description: "Remove an item from a list option in given configuration. If the value appears multiple times, all matching occurrences will be removed."
  }],
  ["rename", {
    name: "rename",
    parameters: [
      { name: "config", type: "string", optional: false },
      { name: "section", type: "string", optional: false },
      { name: "option_or_name", type: "string", optional: false },
      { name: "name", type: "string", optional: true }
    ],
    returnType: "boolean | null",
    description: "Rename an option or section in given configuration. When invoked with four arguments, renames the option. When invoked with three arguments, renames the section."
  }],
  ["reorder", {
    name: "reorder",
    parameters: [
      { name: "config", type: "string", optional: false },
      { name: "section", type: "string", optional: false },
      { name: "index", type: "number", optional: false }
    ],
    returnType: "boolean | null",
    description: "Reorder sections in given configuration. Moves a single section by repositioning it to the given index within the configuration's section list."
  }],
  ["save", {
    name: "save",
    parameters: [
      { name: "config", type: "string", optional: true }
    ],
    returnType: "boolean | null",
    description: "Save accumulated cursor changes to delta directory. When config parameter is omitted, delta records for all currently loaded configuration files are written."
  }],
  ["commit", {
    name: "commit",
    parameters: [
      { name: "config", type: "string", optional: true }
    ],
    returnType: "boolean | null",
    description: "Update configuration files with accumulated cursor changes. When config parameter is omitted, all currently loaded configuration files are updated."
  }],
  ["revert", {
    name: "revert",
    parameters: [
      { name: "config", type: "string", optional: true }
    ],
    returnType: "boolean | null",
    description: "Revert accumulated cursor changes and associated delta records. When config parameter is omitted, all currently loaded configuration files are reverted."
  }],
  ["changes", {
    name: "changes",
    parameters: [
      { name: "config", type: "string", optional: true }
    ],
    // Shape (changes_to_uval / change_to_uval, uci.c): object keyed by config name → array of
    // change records, each record an array `[cmd, section, name?, value?]`. `cmd` is one of
    // "order"/"remove"/"rename"/"add"/"list-add"/"list-del"/"set". Elements are strings, EXCEPT
    // a "order" record's value is an integer. So the precise value shape is
    // `object<string, array<array<string|integer>>>`. The type system has no inline object
    // value-type representation reachable from a return-type string (dict-value typing is
    // inferred from assignments onto a symbol, not from module return strings), so the return
    // stays `object | null` and the structure is documented here rather than modeled unsoundly.
    returnType: "object | null",
    description: "Enumerate pending changes. Returns an object keyed by configuration name; each value is an array of change records. Each record is an array of the form [cmd, section, name?, value?] where cmd is one of \"order\", \"remove\", \"rename\", \"add\", \"list-add\", \"list-del\", \"set\". Record elements are strings, except an \"order\" record's value is an integer."
  }],
  ["foreach", {
    name: "foreach",
    parameters: [
      { name: "config", type: "string", optional: false },
      { name: "type", type: "string", optional: true },
      // The callback is invoked once per section with a single section object argument.
      { name: "callback", type: "function", optional: false, callbackParamTypes: ["object"] }
    ],
    returnType: "boolean | null",
    description: "Iterate configuration sections. The callback is invoked for each encountered section, optionally filtered by type."
  }],
  ["configs", {
    name: "configs",
    parameters: [],
    returnType: "string[] | null",
    description: "Enumerate existing configurations. Returns an array of configuration files present in the cursor's associated configuration directory."
  }],
  ["error", {
    name: "error",
    parameters: [],
    returnType: "string | null",
    description: "Query error information. Returns a string containing a description of the last occurred error or null if there is no error information."
  }]
]);

// Backwards-compat export
export { cursorMethods as uciCursorMethods };

export const uciModule: ModuleDefinition = {
  name: 'uci',
  functions,
  documentation: `## UCI Module

**OpenWrt UCI configuration interface for ucode scripts**

The uci module provides access to the native OpenWrt libuci API for reading and manipulating UCI configuration files.

### Usage

**Named import syntax:**
\`\`\`ucode
import { cursor, error } from 'uci';

let ctx = cursor();
let val = ctx.get('network', 'lan', 'proto');
\`\`\`

**Namespace import syntax:**
\`\`\`ucode
import * as uci from 'uci';

let ctx = uci.cursor();
let val = ctx.get('network', 'lan', 'proto');
\`\`\`

### Available Functions

- **\`error()\`** - Get last error description
- **\`cursor()\`** - Create a UCI cursor for configuration access

### Cursor Methods

- **\`load()\`**, **\`unload()\`** - Load/unload configuration files
- **\`get()\`**, **\`get_all()\`**, **\`get_first()\`** - Query configuration
- **\`set()\`**, **\`add()\`**, **\`delete()\`** - Modify configuration
- **\`list_append()\`**, **\`list_remove()\`** - List operations
- **\`rename()\`**, **\`reorder()\`** - Rename/reorder sections
- **\`save()\`**, **\`commit()\`**, **\`revert()\`** - Persistence
- **\`changes()\`** - Enumerate pending changes
- **\`foreach()\`** - Iterate sections
- **\`configs()\`** - List available configurations

*Hover over individual function names for detailed parameter and return type information.*`,
};

export const uciCursorObjectType: ObjectTypeDefinition = {
  typeName: 'uci.cursor',
  methods: cursorMethods,
  formatDoc: (_name: string, sig: FunctionSignature) => {
    const params = sig.parameters.map(p => {
      if (p.optional && p.defaultValue !== undefined) {
        return `[${p.name}: ${p.type}] = ${p.defaultValue}`;
      } else if (p.optional) {
        return `[${p.name}: ${p.type}]`;
      }
      return `${p.name}: ${p.type}`;
    }).join(', ');

    let doc = `**${sig.name}(${params}): ${sig.returnType}**\n\n${sig.description}\n\n`;

    if (sig.parameters.length > 0) {
      doc += '**Parameters:**\n';
      sig.parameters.forEach(param => {
        const optional = param.optional ? ' (optional)' : '';
        const defaultVal = param.defaultValue !== undefined ? ` (default: ${param.defaultValue})` : '';
        doc += `- \`${param.name}\` (${param.type}${optional}${defaultVal})\n`;
      });
      doc += '\n';
    }

    doc += `**Returns:** \`${sig.returnType}\``;
    return doc;
  },
};

// UCI section object shape, produced by `get_all` (and the `foreach` callback argument).
// Verified against ucode/lib/uci.c `section_to_uval` (and `package_to_uval` for the .index key):
//   - `.anonymous` (boolean) — whether the section is unnamed
//   - `.type`      (string)  — the section type
//   - `.name`      (string)  — the section name
//   - `.index`     (integer) — 0-based position; present ONLY in the 1-arg package form
//                              (section_to_uval is called with index -1 for a single section,
//                              which omits the key; package_to_uval passes a real index)
// Plus one key per option: a string for UCI_TYPE_STRING, an array<string> for UCI_TYPE_LIST
// (option_to_uval). Option keys are config-defined and open-ended, so the type is openMembers:
// an unknown member resolves to `unknown` (NOT UC5004) rather than being flagged.
const sectionMetaKeys = new Map<string, PropertyDefinition>([
  [".anonymous", { name: ".anonymous", type: "boolean", description: "True when the section is anonymous (unnamed)." }],
  [".type", { name: ".type", type: "string", description: "The UCI section type (e.g. \"interface\", \"rule\")." }],
  [".name", { name: ".name", type: "string", description: "The UCI section name. For anonymous sections this is the autogenerated identifier (e.g. \"cfg0392a5\")." }],
  [".index", { name: ".index", type: "integer", description: "The 0-based position of the section within its configuration. Only present when the section is obtained via the 1-argument package form of get_all()." }],
]);

export const uciSectionObjectType: ObjectTypeDefinition = {
  typeName: 'uci.section',
  isPropertyBased: true,
  methods: new Map<string, FunctionSignature>(),
  properties: sectionMetaKeys,
  // Option values are config-defined (string | array<string>); unknown members must not error.
  openMembers: true,
};

export const uciTypeRegistry = {
  getFunctionNames: () => Array.from(functions.keys()),
  getFunction: (name: string) => functions.get(name),
  isUciFunction: (name: string) => functions.has(name),
  getCursorMethodNames: () => Array.from(cursorMethods.keys()),
  getCursorMethod: (name: string) => cursorMethods.get(name),
  isUciCursorMethod: (name: string) => cursorMethods.has(name),
  formatFunctionSignature: (name: string) => {
    const func = functions.get(name);
    if (!func) return '';
    return formatFunctionSignature('uci', func);
  },
  formatCursorMethodSignature: (name: string) => {
    const func = cursorMethods.get(name);
    if (!func) return '';
    return formatFunctionSignature('uci', func);
  },
  getFunctionDocumentation: (name: string) => {
    const func = functions.get(name);
    if (!func) return '';
    return formatFunctionDoc('uci', func);
  },
  getCursorMethodDocumentation: (name: string) => {
    const func = cursorMethods.get(name);
    if (!func) return '';
    return formatFunctionDoc('uci', func);
  },
  isValidImport: (name: string) => functions.has(name),
  getValidImports: () => Array.from(functions.keys()),
};
