/**
 * UCI module type definitions and function signatures
 * Based on ucode/lib/uci.c
 */

import type { FunctionSignature } from './moduleTypes';
import type { ModuleDefinition, ObjectTypeDefinition } from './registryFactory';
import { formatFunctionDoc, formatFunctionSignature } from './registryFactory';
import { UcodeDataType, ModuleType, UcodeType } from './symbolTable';

// Backwards-compat type alias
export type UciFunctionSignature = FunctionSignature;

const functions = new Map<string, FunctionSignature>([
  ["error", {
    name: "error",
    parameters: [],
    returnType: "string | null",
    description: "Returns a string containing a description of the last occurred error or null if there is no error information."
  }],
  ["cursor", {
    name: "cursor",
    parameters: [
      { name: "config_dir", type: "string", optional: true, defaultValue: "/etc/config" },
      { name: "delta_dir", type: "string", optional: true, defaultValue: "/tmp/.uci" },
      { name: "config2_dir", type: "string", optional: true, defaultValue: "/var/run/uci" },
      { name: "flags", type: "object", optional: true }
    ],
    returnType: "uci.cursor | null",
    description: "Instantiate uci cursor. A uci cursor is a context for interacting with uci configuration files."
  }]
]);

// Backwards-compat export
export { functions as uciFunctions };

const cursorMethods = new Map<string, FunctionSignature>([
  ["load", {
    name: "load",
    parameters: [
      { name: "config", type: "string", optional: false }
    ],
    returnType: "boolean | null",
    description: "Explicitly reload configuration file. Returns true if the configuration was successfully loaded."
  }],
  ["unload", {
    name: "unload",
    parameters: [
      { name: "config", type: "string", optional: false }
    ],
    returnType: "boolean | null",
    description: "Explicitly unload configuration file. Returns true if the configuration was successfully unloaded."
  }],
  ["get", {
    name: "get",
    parameters: [
      { name: "config", type: "string", optional: false },
      { name: "section", type: "string", optional: false },
      { name: "option", type: "string", optional: true }
    ],
    returnType: "string | string[] | null",
    description: "Query a single option value or section type. When invoked with three arguments, returns the option value. When invoked with two arguments, returns the section type."
  }],
  ["get_all", {
    name: "get_all",
    parameters: [
      { name: "config", type: "string", optional: false },
      { name: "section", type: "string", optional: true }
    ],
    returnType: "object | null",
    description: "Query a complete section or configuration. When invoked with two arguments, returns all values of the specified section. When invoked with one argument, returns a nested dictionary of all sections."
  }],
  ["get_first", {
    name: "get_first",
    parameters: [
      { name: "config", type: "string", optional: false },
      { name: "type", type: "string", optional: false },
      { name: "option", type: "string", optional: true }
    ],
    returnType: "string | string[] | null",
    description: "Query option value or name of first section of given type. When invoked with three arguments, returns the option value. When invoked with two arguments, returns the section name."
  }],
  ["add", {
    name: "add",
    parameters: [
      { name: "config", type: "string", optional: false },
      { name: "type", type: "string", optional: false }
    ],
    returnType: "string | null",
    description: "Add anonymous section to given configuration. Returns the autogenerated, ephemeral name of the added unnamed section."
  }],
  ["set", {
    name: "set",
    parameters: [
      { name: "config", type: "string", optional: false },
      { name: "section", type: "string", optional: false },
      { name: "option_or_type", type: "string", optional: false },
      { name: "value", type: "string | string[] | number | boolean", optional: true }
    ],
    returnType: "boolean | null",
    description: "Set option value or add named section in given configuration. Returns true if the operation succeeded."
  }],
  ["delete", {
    name: "delete",
    parameters: [
      { name: "config", type: "string", optional: false },
      { name: "section", type: "string", optional: false },
      { name: "option", type: "string", optional: true }
    ],
    returnType: "boolean | null",
    description: "Delete an option or section from given configuration. When invoked with three arguments, deletes the option. When invoked with two arguments, deletes the entire section."
  }],
  ["list_append", {
    name: "list_append",
    parameters: [
      { name: "config", type: "string", optional: false },
      { name: "section", type: "string", optional: false },
      { name: "option", type: "string", optional: false },
      { name: "value", type: "string | number | boolean", optional: false }
    ],
    returnType: "boolean | null",
    description: "Add an item to a list option in given configuration. The new value is appended to the end of the list."
  }],
  ["list_remove", {
    name: "list_remove",
    parameters: [
      { name: "config", type: "string", optional: false },
      { name: "section", type: "string", optional: false },
      { name: "option", type: "string", optional: false },
      { name: "value", type: "string | number | boolean", optional: false }
    ],
    returnType: "boolean | null",
    description: "Remove an item from a list option in given configuration. If the value appears multiple times, all matching occurrences will be removed."
  }],
  ["rename", {
    name: "rename",
    parameters: [
      { name: "config", type: "string", optional: false },
      { name: "section", type: "string", optional: false },
      { name: "option_or_name", type: "string", optional: false },
      { name: "name", type: "string", optional: true }
    ],
    returnType: "boolean | null",
    description: "Rename an option or section in given configuration. When invoked with four arguments, renames the option. When invoked with three arguments, renames the section."
  }],
  ["reorder", {
    name: "reorder",
    parameters: [
      { name: "config", type: "string", optional: false },
      { name: "section", type: "string", optional: false },
      { name: "index", type: "number", optional: false }
    ],
    returnType: "boolean | null",
    description: "Reorder sections in given configuration. Moves a single section by repositioning it to the given index within the configuration's section list."
  }],
  ["save", {
    name: "save",
    parameters: [
      { name: "config", type: "string", optional: true }
    ],
    returnType: "boolean | null",
    description: "Save accumulated cursor changes to delta directory. When config parameter is omitted, delta records for all currently loaded configuration files are written."
  }],
  ["commit", {
    name: "commit",
    parameters: [
      { name: "config", type: "string", optional: true }
    ],
    returnType: "boolean | null",
    description: "Update configuration files with accumulated cursor changes. When config parameter is omitted, all currently loaded configuration files are updated."
  }],
  ["revert", {
    name: "revert",
    parameters: [
      { name: "config", type: "string", optional: true }
    ],
    returnType: "boolean | null",
    description: "Revert accumulated cursor changes and associated delta records. When config parameter is omitted, all currently loaded configuration files are reverted."
  }],
  ["changes", {
    name: "changes",
    parameters: [
      { name: "config", type: "string", optional: true }
    ],
    returnType: "object | null",
    description: "Enumerate pending changes. Returns a dictionary of change record arrays, keyed by configuration name."
  }],
  ["foreach", {
    name: "foreach",
    parameters: [
      { name: "config", type: "string", optional: false },
      { name: "type", type: "string", optional: true },
      { name: "callback", type: "function", optional: false }
    ],
    returnType: "boolean | null",
    description: "Iterate configuration sections. The callback is invoked for each encountered section, optionally filtered by type."
  }],
  ["configs", {
    name: "configs",
    parameters: [],
    returnType: "string[] | null",
    description: "Enumerate existing configurations. Returns an array of configuration files present in the cursor's associated configuration directory."
  }],
  ["error", {
    name: "error",
    parameters: [],
    returnType: "string | null",
    description: "Query error information. Returns a string containing a description of the last occurred error or null if there is no error information."
  }]
]);

// Backwards-compat export
export { cursorMethods as uciCursorMethods };

export enum UciObjectType {
  UCI_CURSOR = 'uci.cursor',
}

export function createUciObjectDataType(type: UciObjectType): ModuleType {
  return {
    type: UcodeType.OBJECT,
    moduleName: type,
  };
}

export const uciModule: ModuleDefinition = {
  name: 'uci',
  functions,
  documentation: `## UCI Module

**OpenWrt UCI configuration interface for ucode scripts**

The uci module provides access to the native OpenWrt libuci API for reading and manipulating UCI configuration files.

### Usage

**Named import syntax:**
\`\`\`ucode
import { cursor, error } from 'uci';

let ctx = cursor();
let val = ctx.get('network', 'lan', 'proto');
\`\`\`

**Namespace import syntax:**
\`\`\`ucode
import * as uci from 'uci';

let ctx = uci.cursor();
let val = ctx.get('network', 'lan', 'proto');
\`\`\`

### Available Functions

- **\`error()\`** - Get last error description
- **\`cursor()\`** - Create a UCI cursor for configuration access

### Cursor Methods

- **\`load()\`**, **\`unload()\`** - Load/unload configuration files
- **\`get()\`**, **\`get_all()\`**, **\`get_first()\`** - Query configuration
- **\`set()\`**, **\`add()\`**, **\`delete()\`** - Modify configuration
- **\`list_append()\`**, **\`list_remove()\`** - List operations
- **\`rename()\`**, **\`reorder()\`** - Rename/reorder sections
- **\`save()\`**, **\`commit()\`**, **\`revert()\`** - Persistence
- **\`changes()\`** - Enumerate pending changes
- **\`foreach()\`** - Iterate sections
- **\`configs()\`** - List available configurations

*Hover over individual function names for detailed parameter and return type information.*`,
};

export const uciCursorObjectType: ObjectTypeDefinition = {
  typeName: 'uci.cursor',
  methods: cursorMethods,
  formatDoc: (_name: string, sig: FunctionSignature) => {
    const params = sig.parameters.map(p => {
      if (p.optional && p.defaultValue !== undefined) {
        return `[${p.name}: ${p.type}] = ${p.defaultValue}`;
      } else if (p.optional) {
        return `[${p.name}: ${p.type}]`;
      }
      return `${p.name}: ${p.type}`;
    }).join(', ');

    let doc = `**${sig.name}(${params}): ${sig.returnType}**\n\n${sig.description}\n\n`;

    if (sig.parameters.length > 0) {
      doc += '**Parameters:**\n';
      sig.parameters.forEach(param => {
        const optional = param.optional ? ' (optional)' : '';
        const defaultVal = param.defaultValue !== undefined ? ` (default: ${param.defaultValue})` : '';
        doc += `- \`${param.name}\` (${param.type}${optional}${defaultVal})\n`;
      });
      doc += '\n';
    }

    doc += `**Returns:** \`${sig.returnType}\``;
    return doc;
  },
};

// Backwards compatibility
class UciCursorObjectRegistry {
  isVariableOfUciType(dataType: UcodeDataType): UciObjectType | null {
    if (typeof dataType === 'object' && 'moduleName' in dataType) {
      const moduleName = (dataType as ModuleType).moduleName;
      if (moduleName === UciObjectType.UCI_CURSOR) {
        return UciObjectType.UCI_CURSOR;
      }
    }
    return null;
  }

  getUciMethod(type: UciObjectType, methodName: string): FunctionSignature | undefined {
    if (type === UciObjectType.UCI_CURSOR) {
      return cursorMethods.get(methodName);
    }
    return undefined;
  }
}

export const uciCursorObjectRegistry = new UciCursorObjectRegistry();

export const uciTypeRegistry = {
  getFunctionNames: () => Array.from(functions.keys()),
  getFunction: (name: string) => functions.get(name),
  isUciFunction: (name: string) => functions.has(name),
  getCursorMethodNames: () => Array.from(cursorMethods.keys()),
  getCursorMethod: (name: string) => cursorMethods.get(name),
  isUciCursorMethod: (name: string) => cursorMethods.has(name),
  formatFunctionSignature: (name: string) => {
    const func = functions.get(name);
    if (!func) return '';
    return formatFunctionSignature('uci', func);
  },
  formatCursorMethodSignature: (name: string) => {
    const func = cursorMethods.get(name);
    if (!func) return '';
    return formatFunctionSignature('uci', func);
  },
  getFunctionDocumentation: (name: string) => {
    const func = functions.get(name);
    if (!func) return '';
    return formatFunctionDoc('uci', func);
  },
  getCursorMethodDocumentation: (name: string) => {
    const func = cursorMethods.get(name);
    if (!func) return '';
    return formatFunctionDoc('uci', func);
  },
  isValidImport: (name: string) => functions.has(name),
  getValidImports: () => Array.from(functions.keys()),
};
