/**
 * uloop module type definitions and function signatures
 * Based on ucode/lib/uloop.c
 *
 * The uloop module provides OpenWrt uloop event loop integration for handling
 * timers, file descriptors, processes, signals, and background tasks.
 */

import type { FunctionSignature } from './moduleTypes';
import type { ModuleDefinition, ConstantDefinition, ObjectTypeDefinition } from './registryFactory';
import { formatFunctionDoc, formatFunctionSignature } from './registryFactory';
import { UcodeType, UcodeDataType } from './symbolTable';

// Backwards-compat type aliases
export type UloopFunctionSignature = FunctionSignature;
export type UloopConstantSignature = ConstantDefinition;

const functions = new Map<string, FunctionSignature>([
  ["error", {
    name: "error",
    parameters: [],
    returnType: "string | null",
    description: "Retrieves the last error message generated by the uloop event loop. Returns null if no error occurred."
  }],
  ["init", {
    name: "init",
    parameters: [],
    returnType: "boolean | null",
    description: `Initializes the uloop event loop, allowing subsequent usage of uloop functionalities. Returns true on success, null on error.

**Example:**
\`\`\`ucode
// Initialize the uloop event loop
if (init())
  printf("uloop initialized successfully\\n");
else
  die(\`Initialization failed: \${error()}\\n\`);
\`\`\``
  }],
  ["run", {
    name: "run",
    parameters: [
      { name: "timeout", type: "integer", optional: true, defaultValue: -1 }
    ],
    returnType: "integer | null",
    description: `Runs the uloop event loop. If timeout is provided and non-negative, runs for that many milliseconds. If timeout is omitted or negative, runs indefinitely until stopped.

**Example:**
\`\`\`ucode
// Run event loop for 5 seconds
run(5000);

// Run event loop indefinitely
run();
\`\`\``
  }],
  ["cancelling", {
    name: "cancelling",
    parameters: [],
    returnType: "boolean",
    description: "Checks if the uloop event loop is currently shutting down. Returns true if shutting down, false otherwise."
  }],
  ["running", {
    name: "running",
    parameters: [],
    returnType: "boolean",
    description: "Checks if the uloop event loop is currently started and running. Returns true if running, false otherwise."
  }],
  ["end", {
    name: "end",
    parameters: [],
    returnType: "null",
    description: "Halts the uloop event loop, stopping its execution. Expired timeouts and already queued event callbacks are still run to completion."
  }],
  ["done", {
    name: "done",
    parameters: [],
    returnType: "null",
    description: "Stops the uloop event loop and cancels pending timeouts and events, unregisters all handles, and deallocates associated resources."
  }],
  ["timer", {
    name: "timer",
    parameters: [
      { name: "timeout", type: "integer", optional: true, defaultValue: -1 },
      { name: "callback", type: "function", optional: false }
    ],
    returnType: "uloop.timer | null",
    description: `Creates a timer instance for scheduling callbacks. Takes an optional timeout in milliseconds and a callback function to execute when the timer expires.

**Example:**
\`\`\`ucode
// Create a timer that fires after 1000ms
let myTimer = timer(1000, () => {
  printf("Timer expired!\\n");
});
\`\`\``
  }],
  ["handle", {
    name: "handle",
    parameters: [
      { name: "handle", type: "integer | fs.file | fs.proc | socket.socket", optional: false },
      { name: "callback", type: "function", optional: false },
      { name: "events", type: "integer", optional: false }
    ],
    returnType: "uloop.handle | null",
    description: `Creates a handle instance for monitoring file descriptor events. Takes a file handle, callback function, and bitwise OR-ed flags of IO events (ULOOP_READ, ULOOP_WRITE).

**Example:**
\`\`\`ucode
// Monitor a file descriptor for read events
let myHandle = handle(3, (events) => {
  if (events & ULOOP_READ)
    printf("Data ready to read!\\n");
}, ULOOP_READ);
\`\`\``
  }],
  ["process", {
    name: "process",
    parameters: [
      { name: "executable", type: "string", optional: false },
      { name: "args", type: "array", optional: true },
      { name: "env", type: "object", optional: true },
      { name: "callback", type: "function", optional: false }
    ],
    returnType: "uloop.process | null",
    description: "Creates a process instance for executing external programs. Takes executable path, optional arguments array, optional environment variables, and callback function."
  }],
  ["task", {
    name: "task",
    parameters: [
      { name: "taskFunction", type: "function", optional: false },
      { name: "outputCallback", type: "function", optional: true },
      { name: "inputCallback", type: "function", optional: true }
    ],
    returnType: "uloop.task | null",
    description: "Creates a task instance for executing background tasks. Takes the task function, optional output callback, and optional input callback."
  }],
  ["interval", {
    name: "interval",
    parameters: [
      { name: "timeout", type: "integer", optional: true, defaultValue: -1 },
      { name: "callback", type: "function", optional: false }
    ],
    returnType: "uloop.interval | null",
    description: "Creates an interval instance for scheduling repeated callbacks. Takes optional interval in milliseconds and callback function to execute repeatedly."
  }],
  ["signal", {
    name: "signal",
    parameters: [
      { name: "signal", type: "string | integer", optional: false },
      { name: "callback", type: "function", optional: false }
    ],
    returnType: "uloop.signal | null",
    description: "Creates a signal instance for handling Unix signals. Takes signal name (with or without 'SIG' prefix) or signal number, and callback function."
  }],
  ["guard", {
    name: "guard",
    parameters: [
      { name: "handler", type: "function", optional: true }
    ],
    returnType: "function | boolean | null",
    description: "Sets or gets the exception handler for uloop callbacks. If no arguments, returns current handler. If handler provided, sets it and returns true."
  }]
]);

// Backwards-compat export
export { functions as uloopFunctions };

const uloopConstants: Map<string, ConstantDefinition> = new Map([
  ["ULOOP_READ", { name: "ULOOP_READ", value: 1, type: "integer", description: "File or socket is readable - used with handle() to monitor read events" }],
  ["ULOOP_WRITE", { name: "ULOOP_WRITE", value: 2, type: "integer", description: "File or socket is writable - used with handle() to monitor write events" }],
  ["ULOOP_EDGE_TRIGGER", { name: "ULOOP_EDGE_TRIGGER", value: 4, type: "integer", description: "Enable edge-triggered event mode - used with handle() for edge-triggered notifications" }],
  ["ULOOP_BLOCKING", { name: "ULOOP_BLOCKING", value: 8, type: "integer", description: "Do not make descriptor non-blocking - used with handle() to keep descriptor in blocking mode" }]
]);

// Backwards-compat export
export { uloopConstants };

export const uloopModule: ModuleDefinition = {
  name: 'uloop',
  functions,
  constants: uloopConstants,
  documentation: `## uloop Module

**OpenWrt uloop event loop module**

Provides event-driven programming capabilities for handling timers, file descriptors, processes, signals, and background tasks.

### Usage

**Named import syntax:**
\`\`\`ucode
import { init, run, timer, handle, ULOOP_READ } from 'uloop';

init();
let t = timer(1000, () => printf("tick\\n"));
run();
\`\`\`

**Namespace import syntax:**
\`\`\`ucode
import * as uloop from 'uloop';

uloop.init();
let t = uloop.timer(1000, () => printf("tick\\n"));
uloop.run();
\`\`\`

### Available Functions

- **\`init()\`** - Initialize the event loop
- **\`run()\`** - Run the event loop
- **\`end()\`** / **\`done()\`** - Stop the event loop
- **\`timer()\`** - Create a one-shot timer
- **\`interval()\`** - Create a repeating interval
- **\`handle()\`** - Monitor file descriptor events
- **\`process()\`** - Launch and monitor external processes
- **\`task()\`** - Run background tasks
- **\`signal()\`** - Handle Unix signals
- **\`guard()\`** - Set exception handler
- **\`cancelling()\`** / **\`running()\`** - Query event loop state
- **\`error()\`** - Get last error message

### Constants

**Event flags:** ULOOP_READ, ULOOP_WRITE, ULOOP_EDGE_TRIGGER, ULOOP_BLOCKING

*Hover over individual function names for detailed parameter and return type information.*`,
};

// ============================================================================
// Uloop Object Types (timer, handle, process, task, interval, signal, pipe)
// ============================================================================

export enum UloopObjectType {
  ULOOP_TIMER = 'uloop.timer',
  ULOOP_HANDLE = 'uloop.handle',
  ULOOP_PROCESS = 'uloop.process',
  ULOOP_TASK = 'uloop.task',
  ULOOP_INTERVAL = 'uloop.interval',
  ULOOP_SIGNAL = 'uloop.signal',
  ULOOP_PIPE = 'uloop.pipe'
}

const timerMethods = new Map<string, FunctionSignature>([
  ['set', {
    name: 'set',
    parameters: [{ name: 'timeout', type: 'integer', optional: true, defaultValue: -1 }],
    returnType: 'boolean | null',
    description: 'Rearms the uloop timer with the specified timeout in milliseconds. Returns true on success, null on error.'
  }],
  ['remaining', {
    name: 'remaining',
    parameters: [],
    returnType: 'integer',
    description: 'Returns the number of milliseconds until the timer expires, or -1 if the timer is not armed.'
  }],
  ['cancel', {
    name: 'cancel',
    parameters: [],
    returnType: 'boolean',
    description: 'Cancels the uloop timer, disarming it and removing it from the event loop. Returns true on success.'
  }]
]);

const handleMethods = new Map<string, FunctionSignature>([
  ['fileno', {
    name: 'fileno',
    parameters: [],
    returnType: 'integer',
    description: 'Returns the file descriptor number associated with the handle.'
  }],
  ['handle', {
    name: 'handle',
    parameters: [],
    returnType: 'fs.file | fs.proc | socket.socket',
    description: 'Returns the underlying file or socket instance associated with the uloop handle.'
  }],
  ['delete', {
    name: 'delete',
    parameters: [],
    returnType: 'null',
    description: 'Unregisters the uloop handle from the event loop and frees associated resources.'
  }]
]);

const processMethods = new Map<string, FunctionSignature>([
  ['pid', {
    name: 'pid',
    parameters: [],
    returnType: 'integer',
    description: 'Returns the process ID (PID) of the operating system process launched by process().'
  }],
  ['delete', {
    name: 'delete',
    parameters: [],
    returnType: 'boolean',
    description: 'Unregisters the process from the uloop event loop and releases associated resources. Returns true on success.'
  }]
]);

const taskMethods = new Map<string, FunctionSignature>([
  ['pid', {
    name: 'pid',
    parameters: [],
    returnType: 'integer',
    description: 'Returns the process ID (PID) of the underlying forked process launched by task().'
  }],
  ['kill', {
    name: 'kill',
    parameters: [],
    returnType: 'boolean | null',
    description: 'Terminates the task process by sending SIGTERM. Returns true on success, null on error.'
  }],
  ['finished', {
    name: 'finished',
    parameters: [],
    returnType: 'boolean',
    description: 'Checks if the task function has already run to completion. Returns true if finished, false otherwise.'
  }]
]);

const intervalMethods = new Map<string, FunctionSignature>([
  ['set', {
    name: 'set',
    parameters: [{ name: 'interval', type: 'integer', optional: true, defaultValue: -1 }],
    returnType: 'boolean | null',
    description: 'Rearms the uloop interval with the specified interval in milliseconds. Returns true on success, null on error.'
  }],
  ['remaining', {
    name: 'remaining',
    parameters: [],
    returnType: 'integer',
    description: 'Returns the milliseconds until the next expiration of the interval, or -1 if not armed.'
  }],
  ['expirations', {
    name: 'expirations',
    parameters: [],
    returnType: 'integer',
    description: 'Returns the number of times the interval timer has expired (fired) since instantiation.'
  }],
  ['cancel', {
    name: 'cancel',
    parameters: [],
    returnType: 'boolean',
    description: 'Cancels the uloop interval, disarming it and removing it from the event loop. Returns true on success.'
  }]
]);

const signalMethods = new Map<string, FunctionSignature>([
  ['signo', {
    name: 'signo',
    parameters: [],
    returnType: 'integer',
    description: 'Returns the signal number that this uloop signal handler is configured to respond to.'
  }],
  ['delete', {
    name: 'delete',
    parameters: [],
    returnType: 'boolean',
    description: 'Uninstalls the signal handler, restoring the previous or default handler for the signal. Returns true on success.'
  }]
]);

const pipeMethods = new Map<string, FunctionSignature>([
  ['send', {
    name: 'send',
    parameters: [{ name: 'msg', type: 'any', optional: false }],
    returnType: 'boolean | null',
    description: 'Sends a serialized message to the task handle. Returns true on success, null on error.'
  }],
  ['receive', {
    name: 'receive',
    parameters: [],
    returnType: 'any | null',
    description: 'Reads input from the task communication pipe. Returns the deserialized message or null on error.'
  }],
  ['sending', {
    name: 'sending',
    parameters: [],
    returnType: 'boolean',
    description: 'Checks if the remote task handle has an input callback registered. Returns true if available, false otherwise.'
  }],
  ['receiving', {
    name: 'receiving',
    parameters: [],
    returnType: 'boolean',
    description: 'Checks if the task handle has an output callback registered. Returns true if available, false otherwise.'
  }]
]);

// Object type definitions for factory
export const uloopTimerObjectType: ObjectTypeDefinition = { typeName: 'uloop.timer', methods: timerMethods };
export const uloopHandleObjectType: ObjectTypeDefinition = { typeName: 'uloop.handle', methods: handleMethods };
export const uloopProcessObjectType: ObjectTypeDefinition = { typeName: 'uloop.process', methods: processMethods };
export const uloopTaskObjectType: ObjectTypeDefinition = { typeName: 'uloop.task', methods: taskMethods };
export const uloopIntervalObjectType: ObjectTypeDefinition = { typeName: 'uloop.interval', methods: intervalMethods };
export const uloopSignalObjectType: ObjectTypeDefinition = { typeName: 'uloop.signal', methods: signalMethods };
export const uloopPipeObjectType: ObjectTypeDefinition = { typeName: 'uloop.pipe', methods: pipeMethods };

export function isUloopObjectType(typeName: string): typeName is UloopObjectType {
  return Object.values(UloopObjectType).includes(typeName as UloopObjectType);
}

export function createUloopObjectDataType(uloopType: UloopObjectType): UcodeDataType {
  return {
    type: UcodeType.OBJECT,
    moduleName: uloopType
  };
}

// Map of all uloop object type methods for backwards-compat
const objectMethodMaps: Record<string, Map<string, FunctionSignature>> = {
  [UloopObjectType.ULOOP_TIMER]: timerMethods,
  [UloopObjectType.ULOOP_HANDLE]: handleMethods,
  [UloopObjectType.ULOOP_PROCESS]: processMethods,
  [UloopObjectType.ULOOP_TASK]: taskMethods,
  [UloopObjectType.ULOOP_INTERVAL]: intervalMethods,
  [UloopObjectType.ULOOP_SIGNAL]: signalMethods,
  [UloopObjectType.ULOOP_PIPE]: pipeMethods,
};

// Backwards compatibility
export const uloopTypeRegistry = {
  getFunctionNames: () => Array.from(functions.keys()),
  getFunction: (name: string) => functions.get(name),
  isUloopFunction: (name: string) => functions.has(name),
  getConstantNames: () => Array.from(uloopConstants.keys()),
  getConstant: (name: string) => uloopConstants.get(name),
  isUloopConstant: (name: string) => uloopConstants.has(name),
  formatFunctionSignature: (name: string) => {
    const func = functions.get(name);
    if (!func) return '';
    return formatFunctionSignature('uloop', func);
  },
  getFunctionDocumentation: (name: string) => {
    const func = functions.get(name);
    if (!func) return '';
    return formatFunctionDoc('uloop', func);
  },
  getConstantDocumentation: (name: string) => {
    const constant = uloopConstants.get(name);
    if (!constant) return '';
    return `**${constant.name}** = \`${constant.value}\`\n\n*${constant.type}*\n\n${constant.description}`;
  },
  isValidImport: (name: string) => functions.has(name) || uloopConstants.has(name),
  getValidImports: () => [...Array.from(functions.keys()), ...Array.from(uloopConstants.keys())],
};

export const uloopObjectRegistry = {
  getUloopType: (typeName: string) => {
    const methods = objectMethodMaps[typeName];
    if (!methods) return undefined;
    return { type: typeName as UloopObjectType, methods };
  },
  isUloopType: (typeName: string) => typeName in objectMethodMaps,
  getUloopMethod: (typeName: string, methodName: string) => {
    const methods = objectMethodMaps[typeName];
    return methods?.get(methodName);
  },
  getMethodsForType: (typeName: string) => {
    const methods = objectMethodMaps[typeName];
    return methods ? Array.from(methods.keys()) : [];
  },
  isVariableOfUloopType: (dataType: any): UloopObjectType | null => {
    if (typeof dataType === 'string') return null;
    if ('moduleName' in dataType && typeof dataType.moduleName === 'string') {
      if (dataType.moduleName in objectMethodMaps) {
        return dataType.moduleName as UloopObjectType;
      }
    }
    return null;
  },
};
